version: '3'

services:
  db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 1q2w3e
       MYSQL_DATABASE: categories
       MYSQL_USER: django_user
       MYSQL_PASSWORD: django_user
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
   db_data:
