version: '3'

services:
  db:
     image: mysql:8
     volumes:
       - db_data:/var/lib/mysql
       - ./dockerfiles/init_db:/docker-entrypoint-initdb.d
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 1q2w3e
       MYSQL_DATABASE: categories
       MYSQL_USER: django_user
       MYSQL_PASSWORD: django_user
  web:
    build: .
    command: bash -c "/wait-for-it/wait-for-it.sh db:3306 -s --timeout=120 -- python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
   db_data:
