# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0002_auto_20171129_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='categories_app.Category'),
        ),
    ]
